# Generated by Django 4.1.3 on 2023-09-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qrcodes',
            fields=[
                ('qrcode_id', models.AutoField(primary_key=True, serialize=False)),
                ('text_input', models.CharField(blank=True, max_length=500, null=True, verbose_name='ورودی متن')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='media/qrimages/')),
            ],
            options={
                'verbose_name': 'کد کیو آر',
                'verbose_name_plural': 'کد های کی آر',
            },
        ),
    ]
