# Generated by Django 4.1.3 on 2023-09-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='qrcodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_input', models.CharField(max_length=500, verbose_name='ورودی متن')),
                ('link_input', models.CharField(max_length=500, verbose_name='ورودی لینک')),
            ],
            options={
                'verbose_name': 'کد کیو آر',
                'verbose_name_plural': 'کد های کی آر',
            },
        ),
    ]
