# Generated by Django 4.1.3 on 2023-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_maker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='link_input',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ورودی لینک'),
        ),
        migrations.AlterField(
            model_name='qrcodes',
            name='text_input',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ورودی متن'),
        ),
    ]
