# Generated by Django 4.1.3 on 2023-09-12 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_maker', '0002_alter_qrcodes_link_input_alter_qrcodes_text_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodes',
            name='link_input',
        ),
    ]
