# Generated by Django 4.1.3 on 2023-09-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrcode_maker', '0003_remove_qrcodes_link_input'),
    ]

    operations = [
        migrations.CreateModel(
            name='userqrimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='medias/images/qrcodes')),
            ],
            options={
                'verbose_name': 'تصاویر کیو ار کد کاربر',
                'verbose_name_plural': 'تصویر های کیو آر کد کاربران',
            },
        ),
    ]
