# Generated by Django 4.1.3 on 2023-09-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=300, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=400, verbose_name='ایمیل شما')),
                ('message', models.TextField(max_length=2000, verbose_name='متن شما')),
            ],
            options={
                'verbose_name': 'ارتباط با ما',
                'verbose_name_plural': 'ارتباط ها با ما ',
                'default_related_name': 'ارتباط با ما',
            },
        ),
    ]
